<?php
/**
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 */

/**
 * @category   TechDivision
 * @package    PayoneMockable
 * @copyright  Copyright (c) 2018 TechDivision GmbH (http://www.techdivision.com)
 * @link       http://www.techdivision.com/
 * @author     Vadim Justus <v.justus@techdivision.com
 */
?>

<script type="text/javascript" src="https://psp-mock.test/payone/client-api/js/ajax.js"></script>
<script type="text/javascript" src="https://psp-mock.test/payone/client-api/js/v1/payone_hosted_min.js"></script>
<script type="text/javascript" src="https://cdn.klarna.com/public/kitt/core/v1.0/js/klarna.min.js"></script>
<script type="text/javascript" src="https://cdn.klarna.com/public/kitt/toc/v1.1/js/klarna.terms.min.js"></script>

<!--
<script type="text/javascript" src="https://psp-mock.test/payone/client-api/js/ajax.js"></script>
<script type="text/javascript" src="https://psp-mock.test/payone/client-api/js/v1/payone_hosted_min.js"></script>
<script type="text/javascript" src="https://psp-mock.test/klarna/public/kitt/core/v1.0/js/klarna.min.js"></script>
<script type="text/javascript" src="https://psp-mock.test/klarna/public/kitt/toc/v1.1/js/klarna.terms.min.js"></script>
-->
